name: "JIRA ticket in PR Title"

on:
  pull_request:
    branches: [ "**" ]

jobs:
  check-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        if ! grep -qE 'EEPD-[0-9]{5,}' <<< "$TITLE" ; then
          echo Pull request title does not contain a JIRA ticket
          exit 1
        fi
